### ISSUE TITLE
Some objects fail to index

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/dor_indexing_app#610]
**Describe the bug**

See https://app.honeybadger.io/projects/49898/faults/78909143

Noticed when the h2 integration test failed: 

`rspec ./spec/features/create_object_h2_spec.rb:12`

```
Failures:

  1) Use H2 to create an object is expected to have text "https://purl-stage.stanford.edu"
     Failure/Error: click_link item_title

     Capybara::ElementNotFound:
       Unable to find link "SUL Logo for fecundity" within #<Capybara::Node::Element tag="div" path="/HTML/BODY[1]/MAIN[1]/DIV[3]/SECTION[1]/DIV[2]">
     # /Users/petucket/.rvm/gems/ruby-2.7.1/gems/capybara-3.35.3/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
     # /Users/petucket/.rvm/gems/ruby-2.7.1/gems/capybara-3.35.3/lib/capybara/node/base.rb:83:in `synchronize'
     # /Users/petucket/.rvm/gems/ruby-2.7.1/gems/capybara-3.35.3/lib/capybara/node/finders.rb:292:in `synced_resolve'
     # /Users/petucket/.rvm/gems/ruby-2.7.1/gems/capybara-3.35.3/lib/capybara/node/finders.rb:53:in `find'
     # /Users/petucket/.rvm/gems/ruby-2.7.1/gems/capybara-3.35.3/lib/capybara/node/actions.rb:42:in `click_link'
     # /Users/petucket/.rvm/gems/ruby-2.7.1/gems/capybara-3.35.3/lib/capybara/session.rb:762:in `click_link'
     # /Users/petucket/.rvm/gems/ruby-2.7.1/gems/capybara-3.35.3/lib/capybara/dsl.rb:53:in `call'
     # /Users/petucket/.rvm/gems/ruby-2.7.1/gems/capybara-3.35.3/lib/capybara/dsl.rb:53:in `click_link'
     # ./spec/features/create_object_h2_spec.rb:81:in `block (3 levels) in <top (required)>'
     # /Users/petucket/.rvm/gems/ruby-2.7.1/gems/capybara-3.35.3/lib/capybara/session.rb:353:in `within'
     # /Users/petucket/.rvm/gems/ruby-2.7.1/gems/capybara-3.35.3/lib/capybara/dsl.rb:53:in `call'
     # /Users/petucket/.rvm/gems/ruby-2.7.1/gems/capybara-3.35.3/lib/capybara/dsl.rb:53:in `within_element'
     # /Users/petucket/.rvm/gems/ruby-2.7.1/gems/capybara-3.35.3/lib/capybara/rspec/matcher_proxies.rb:15:in `within'
     # ./spec/features/create_object_h2_spec.rb:80:in `block (2 levels) in <top (required)>'
```

The failure manifests as the object not being present in argo even though it is created in H2 and has a PURL

e.g. this object created by the integration test: https://sul-h2-stage.stanford.edu/works/13358
has a PURL: https://sul-purl-stage.stanford.edu/ps141zf3169
but ain't in Argo: https://argo-stage.stanford.edu/view/druid:ps141zf3169  which causes the integration test to fail when it looks for it there

**User Impact**
If objects aren't indexed properly, they won't appear in Argo.

**Comment by peetucket** [comment]
On dor-indexing-app-stage, examining the H2 object from the integration tests that failed:

```
cocina = Dor::Services::Client.object('druid:ps141zf3169').find
indexer = DescriptiveMetadataIndexer.new(cocina: cocina)
puts indexer.to_solr
Traceback (most recent call last):
        5: from (irb):11
        4: from app/indexers/descriptive_metadata_indexer.rb:16:in `to_solr'
        3: from app/indexers/descriptive_metadata_indexer.rb:114:in `sw_format'
        2: from app/indexers/descriptive_metadata_indexer.rb:114:in `map'
        1: from app/indexers/descriptive_metadata_indexer.rb:114:in `block in sw_format'
NoMethodError (undefined method `downcase' for nil:NilClass)
```

**Comment by peetucket** [comment]
Potentially interesting part of the MODs for that object:

```
<genre type="H2 type">Image</genre>
<genre valueURI="http://id.loc.gov/authorities/genreForms/gf2017027251" authority="lcgft">Pictures</genre>
<typeOfResource>still image</typeOfResource>
```

**Comment by peetucket** [comment]
The cocina we generated for that object: 

```
{
   "type":"http://cocina.sul.stanford.edu/models/image.jsonld",
   "externalIdentifier":"druid:ps141zf3169",
   "label":"SUL Logo for fecundity",
   "version":1,
   "access":{
      "access":"world",
      "copyright":"This work is copyrighted by the creator.",
      "download":"world",
      "useAndReproductionStatement":"The standard self-deposit use and reproduction language should go here"
   },
   "administrative":{
      "hasAdminPolicy":"druid:zw306xn5593",
      "partOfProject":"H2"
   },
   "description":{
      "title":[
         {
            "value":"SUL Logo for fecundity"
         }
      ],
      "contributor":[
         {
            "name":[
               {
                  "structuredValue":[
                     {
                        "value":"Dana",
                        "type":"forename"
                     },
                     {
                        "value":"Scully",
                        "type":"surname"
                     }
                  ]
               }
            ],
            "type":"person",
            "status":"primary",
            "role":[
               {
                  "value":"author",
                  "code":"aut",
                  "uri":"http://id.loc.gov/vocabulary/relators/aut",
                  "source":{
                     "code":"marcrelator",
                     "uri":"http://id.loc.gov/vocabulary/relators/"
                  }
               }
            ]
         }
      ],
      "form":[
         {
            "structuredValue":[
               {
                  "value":"Image",
                  "type":"type"
               }
            ],
            "type":"resource type",
            "source":{
               "value":"Stanford self-deposit resource types"
            }
         },
         {
            "value":"Pictures",
            "type":"genre",
            "uri":"http://id.loc.gov/authorities/genreForms/gf2017027251",
            "source":{
               "code":"lcgft"
            }
         },
         {
            "value":"still image",
            "type":"resource type",
            "source":{
               "value":"MODS resource types"
            }
         }
      ],
      "note":[
         {
            "value":"An abstract for fecundity logo",
            "type":"summary"
         },
         {
            "value":"Scully, D. (2021). SUL Logo for fecundity. Stanford Digital Repository. Available at http://purl.stanford.edu/ps141zf3169",
            "type":"preferred citation"
         }
      ],
      "subject":[
         {
            "value":"Integration test",
            "type":"topic"
         }
      ],
      "purl":"http://purl.stanford.edu/ps141zf3169",
      "access":{
         "accessContact":[
            {
               "value":"petucket@stanford.edu",
               "type":"email",
               "displayLabel":"Contact"
            }
         ],
         "digitalRepository":[
            {
               "value":"Stanford Digital Repository"
            }
         ]
      }
   },
   "identification":{
      "sourceId":"hydrus:object-13358"
   },
   "structural":{
      "contains":[
         {
            "type":"http://cocina.sul.stanford.edu/models/resources/file.jsonld",
            "externalIdentifier":"http://cocina.sul.stanford.edu/fileSet/4141c47a-0637-4020-9ef9-52ce3c26d542",
            "label":"",
            "version":1,
            "structural":{
               "contains":[
                  {
                     "type":"http://cocina.sul.stanford.edu/models/file.jsonld",
                     "externalIdentifier":"http://cocina.sul.stanford.edu/file/71fbe1e1-f23e-406e-9901-c1bbac41b83f",
                     "label":"sul-logo.png",
                     "filename":"sul-logo.png",
                     "size":19823,
                     "version":1,
                     "hasMimeType":"image/png",
                     "hasMessageDigests":[
                        {
                           "type":"sha1",
                           "digest":"b5f3221455c8994afb85214576bc2905d6b15418"
                        },
                        {
                           "type":"md5",
                           "digest":"7142ce948827c16120cc9e19b05acd49"
                        }
                     ],
                     "access":{
                        "access":"world",
                        "download":"world"
                     },
                     "administrative":{
                        "publish":true,
                        "sdrPreserve":true,
                        "shelve":true
                     }
                  }
               ]
            }
         }
      ],
      "isMemberOf":[
         "druid:dj969yj8886"
      ]
   }
}
```
