### ISSUE TITLE
Add testing around fixed exception; investigate H2 object

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/dor_indexing_app#612]
#610 fixed a bug ... but we don't have test coverage on this and we don't know why it's being generated.  We should investigate this.

This H2 object triggered the error and was created by the integration test: https://sul-h2-stage.stanford.edu/works/13358
it has a PURL: https://sul-purl-stage.stanford.edu/ps141zf3169
But didn't make it to Argo: https://argo-stage.stanford.edu/view/druid:ps141zf3169 which causes the integration test to fail when it looks for it there

it is also possible the H2 object is not being created correctly.  From Andrew in slack: https://stanfordlib.slack.com/archives/C09M7P91R/p1618608161355700

```how is H2 generating the image content type? it should only be sending content type file and the broken viewer presentation at the Purl it created is a good example of why```

HB error triggered: https://app.honeybadger.io/projects/49898/faults/78909143

Note this error is not triggered anymore because we guard against it.

**Comment by peetucket** [comment]
This is some context (copied from #610).  Basically the integration test caused an H2 created object to fail indexing:

```
cocina = Dor::Services::Client.object('druid:ps141zf3169').find
indexer = DescriptiveMetadataIndexer.new(cocina: cocina)
puts indexer.to_solr
Traceback (most recent call last):
        5: from (irb):11
        4: from app/indexers/descriptive_metadata_indexer.rb:16:in `to_solr'
        3: from app/indexers/descriptive_metadata_indexer.rb:114:in `sw_format'
        2: from app/indexers/descriptive_metadata_indexer.rb:114:in `map'
        1: from app/indexers/descriptive_metadata_indexer.rb:114:in `block in sw_format'
NoMethodError (undefined method `downcase' for nil:NilClass)
```

Start examining output near the exception to find the nil:
```
puts indexer.send(:flat_forms_for,'resource type')
 => [#<Cocina::Models::DescriptiveValue structuredValue=[#<Cocina::Models::DescriptiveValue structuredValue=nil parallelValue=nil groupedValue=nil value="Image" type="type" status=nil code=nil uri=nil standard=nil encoding=nil identifier=nil source=nil displayLabel=nil qualifier=nil note=nil valueLanguage=nil valueAt=nil appliesTo=nil>] parallelValue=nil groupedValue=nil value=nil type="resource type" status=nil code=nil uri=nil standard=nil encoding=nil identifier=nil source=#<#<Class:0x00000000074f6dc8> code=nil uri=nil value="Stanford self-deposit resource types" note=nil version=nil> displayLabel=nil qualifier=nil note=nil valueLanguage=nil valueAt=nil appliesTo=nil>, #<Cocina::Models::DescriptiveValue structuredValue=nil parallelValue=nil groupedValue=nil value="still image" type="resource type" status=nil code=nil uri=nil standard=nil encoding=nil identifier=nil source=#<#<Class:0x00000000074f6dc8> code=nil uri=nil value="MODS resource types" note=nil version=nil> displayLabel=nil qualifier=nil note=nil valueLanguage=nil valueAt=nil appliesTo=nil>]

indexer.send(:flat_forms_for,'resource type').map {|form| form.value}
 => [nil, "still image"]
```
